apiVersion: v1
kind: Service
metadata:
  name: tung-nodeport-svc
  labels:
    app: tung-app-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    type: backend